version: '3'

services:
    ctf:
        restart: always
        build: ./
        read_only: true
    proxy:
        restart: always
        image: nginx
        ports:
            - '31622:31622'
        volumes:
            - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - ctf

