version: "3"
services:
  redis:
    image: redis:7.0
    restart: always

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tfg54y65j67gh5676fk8g755g6j6vb7inbv56
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db_after_dmoj:/initafterdmoj
    ports:
      - 3306:3306

  web:
    image: satosjp/dmoj-site
    container_name: web
    stdin_open: true
    tty: true
    environment:
      - DB_DATABASE=dmoj
      - DB_HOST=db
      - DB_USER=dmoj
      - DB_PASSWORD=t673gh8o034t435y4it34r38ce3ko45t4ij95yh4
      - TZ=Asia/Tokyo
      - DEBUG=false # true/false
      - TWO_STEP_REGISTRATION=false # true/false false の場合はメール認証無し
    volumes:
      - ./sitejsondata:/home/ubuntu/addedjsondata
      - ./sitestatic:/home/ubuntu/addedstaticdata
    ports:
      - 80:80
      - 8000:8000
      - 9999:9999
    depends_on:
      - db
      - redis

  webproblem:
    restart: always
    build: ./webproblem/
    volumes:
      - ./webproblem/src/supervisord.conf:/etc/supervisord.conf:ro
    depends_on:
      - db

  cryproblem:
    restart: always
    build: ./cryproblem/
    volumes:
      - ./cryproblem/src/supervisord.conf:/etc/supervisord.conf:ro

  # judger:
  #   image: satosjp/dmoj-judger
  #   restart: always
  #   volumes:
  #     - ./problems:/home/judge/problems
  #   tty: true
  #   cap_add:
  #     - SYS_PTRACE
  #   network_mode: host
  #   environment:
  #     - PROBLEM_PATH=/home/judge/problems
  #     - SITE_HOST=localhost
  #     - JUDGE_NAME=Judge
  #     - JUDGE_KEY=azrJwgc8tFNjivAbnIDMGIzWDr5fcbdRx7L8gAdnwXXkBLBQXgIbo5BTUaE5lFnDyBfGzw9LaXjG0kteduEQaKul9rUaoNcd
  #   depends_on:
  #     - web


